[language-server.rust-analyzer]
command = "rust-analyzer"
config = { cargo = { features = "all" }, check = { command = "clippy" }, hover = { memoryLayout = { enabled = true } } }

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
roots = ["Cargo.toml", "Cargo.lock"]
formatter = { command = 'rustfmt', args = ["--edition=2024"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true
