[language-server.rust-analyzer]
command = "rust-analyzer"
config = { check = { command = "check" } }

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
formatter = { command = 'rustfmt' }
auto-format = true

